version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "9090:80"
    depends_on:
      - service1
      - service2

  service1:
    build: ./service_1
    expose:
      - "8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  service2:
    build: ./service_2
    expose:
      - "8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 10s
      timeout: 3s
      retries: 3
